apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: do-kubernetes-sample-ingress
spec:
  rules:
  - host: www.wearefrontend.com
    http:
      paths:
      - path: /
        backend:
          serviceName: do-kubernetes-sample-app
          servicePort: 80
